// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {player} from '../models';
import {sqlc} from '../models';
import {http} from '../models';

export function GetAllCourses():Promise<Array<any>>;

export function GetAppSettings():Promise<Record<string, string>>;

export function GetDatabasePath():Promise<string>;

export function GetLectureForPlayer(arg1:number):Promise<player.LectureInfo>;

export function GetLectureProgress(arg1:number):Promise<sqlc.Progress>;

export function GetResumePosition(arg1:number):Promise<number>;

export function GetVideoResumePosition(arg1:number):Promise<number>;

export function Greet(arg1:string):Promise<string>;

export function IsTrackingProgress():Promise<boolean>;

export function ServeHTTP(arg1:http.ResponseWriter,arg2:http.Request):Promise<void>;

export function StartLectureWatch(arg1:number):Promise<void>;

export function StartTrackingProgress(arg1:number):Promise<void>;

export function StopTrackingProgress():Promise<void>;

export function UpdateVideoProgress(arg1:number,arg2:number,arg3:number):Promise<void>;
