// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CompleteOnboarding() {
  return window['go']['main']['App']['CompleteOnboarding']();
}

export function GetAllCourses() {
  return window['go']['main']['App']['GetAllCourses']();
}

export function GetAppSettings() {
  return window['go']['main']['App']['GetAppSettings']();
}

export function GetCourseWithSections(arg1) {
  return window['go']['main']['App']['GetCourseWithSections'](arg1);
}

export function GetCoursesDirectory() {
  return window['go']['main']['App']['GetCoursesDirectory']();
}

export function GetDatabasePath() {
  return window['go']['main']['App']['GetDatabasePath']();
}

export function GetLectureForPlayer(arg1) {
  return window['go']['main']['App']['GetLectureForPlayer'](arg1);
}

export function GetLectureProgress(arg1) {
  return window['go']['main']['App']['GetLectureProgress'](arg1);
}

export function GetResumePosition(arg1) {
  return window['go']['main']['App']['GetResumePosition'](arg1);
}

export function GetSettingValue(arg1) {
  return window['go']['main']['App']['GetSettingValue'](arg1);
}

export function GetTheme() {
  return window['go']['main']['App']['GetTheme']();
}

export function GetVideoResumePosition(arg1) {
  return window['go']['main']['App']['GetVideoResumePosition'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImportCourse(arg1) {
  return window['go']['main']['App']['ImportCourse'](arg1);
}

export function IsFirstRun() {
  return window['go']['main']['App']['IsFirstRun']();
}

export function IsTrackingProgress() {
  return window['go']['main']['App']['IsTrackingProgress']();
}

export function ScanCourseFolder(arg1) {
  return window['go']['main']['App']['ScanCourseFolder'](arg1);
}

export function SelectFolderDialog(arg1) {
  return window['go']['main']['App']['SelectFolderDialog'](arg1);
}

export function ServeHTTP(arg1, arg2) {
  return window['go']['main']['App']['ServeHTTP'](arg1, arg2);
}

export function SetCoursesDirectory(arg1) {
  return window['go']['main']['App']['SetCoursesDirectory'](arg1);
}

export function SetSettingValue(arg1, arg2) {
  return window['go']['main']['App']['SetSettingValue'](arg1, arg2);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function StartLectureWatch(arg1) {
  return window['go']['main']['App']['StartLectureWatch'](arg1);
}

export function StartTrackingProgress(arg1) {
  return window['go']['main']['App']['StartTrackingProgress'](arg1);
}

export function StopTrackingProgress() {
  return window['go']['main']['App']['StopTrackingProgress']();
}

export function UpdateVideoProgress(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateVideoProgress'](arg1, arg2, arg3);
}
