// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllCourses() {
  return window['go']['main']['App']['GetAllCourses']();
}

export function GetAppSettings() {
  return window['go']['main']['App']['GetAppSettings']();
}

export function GetDatabasePath() {
  return window['go']['main']['App']['GetDatabasePath']();
}

export function GetLectureForPlayer(arg1) {
  return window['go']['main']['App']['GetLectureForPlayer'](arg1);
}

export function GetLectureProgress(arg1) {
  return window['go']['main']['App']['GetLectureProgress'](arg1);
}

export function GetResumePosition(arg1) {
  return window['go']['main']['App']['GetResumePosition'](arg1);
}

export function GetVideoResumePosition(arg1) {
  return window['go']['main']['App']['GetVideoResumePosition'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IsTrackingProgress() {
  return window['go']['main']['App']['IsTrackingProgress']();
}

export function ServeHTTP(arg1, arg2) {
  return window['go']['main']['App']['ServeHTTP'](arg1, arg2);
}

export function StartLectureWatch(arg1) {
  return window['go']['main']['App']['StartLectureWatch'](arg1);
}

export function StartTrackingProgress(arg1) {
  return window['go']['main']['App']['StartTrackingProgress'](arg1);
}

export function StopTrackingProgress() {
  return window['go']['main']['App']['StopTrackingProgress']();
}

export function UpdateVideoProgress(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateVideoProgress'](arg1, arg2, arg3);
}
