// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {course} from '../models';
import {player} from '../models';
import {sqlc} from '../models';
import {http} from '../models';

export function CompleteOnboarding():Promise<void>;

export function GetAllCourses():Promise<Array<any>>;

export function GetAppSettings():Promise<Record<string, string>>;

export function GetCourseWithSections(arg1:number):Promise<course.CourseWithSections>;

export function GetCoursesDirectory():Promise<string>;

export function GetDatabasePath():Promise<string>;

export function GetLectureForPlayer(arg1:number):Promise<player.LectureInfo>;

export function GetLectureProgress(arg1:number):Promise<sqlc.Progress>;

export function GetResumePosition(arg1:number):Promise<number>;

export function GetSettingValue(arg1:string):Promise<string>;

export function GetSubfolders(arg1:string):Promise<Array<string>>;

export function GetTheme():Promise<string>;

export function GetVideoResumePosition(arg1:number):Promise<number>;

export function IsFirstRun():Promise<boolean>;

export function IsTrackingProgress():Promise<boolean>;

export function ScanLibrary():Promise<course.ScanLibraryResult>;

export function SelectFolderDialog(arg1:string):Promise<string>;

export function ServeHTTP(arg1:http.ResponseWriter,arg2:http.Request):Promise<void>;

export function SetCoursesDirectory(arg1:string):Promise<void>;

export function SetSettingValue(arg1:string,arg2:string):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function StartLectureWatch(arg1:number):Promise<void>;

export function StartTrackingProgress(arg1:number):Promise<void>;

export function StopTrackingProgress():Promise<void>;

export function UpdateVideoProgress(arg1:number,arg2:number,arg3:number):Promise<void>;
